---

- hosts: labb
  become: true
  tasks:


  - name: Install apache package & php
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes

