---

- hosts: all
  become: true
  pre_tasks:

   - name: install updates (CentOS)
     tags: always
     yum: 
      update_only: yes
      update_cache: yes
     when: ansible_distribution == "CentOS"

   - name: install updates (Ubuntu)
     tags: always
     apt:
       upgrade: dist
       update_cache: yes
     when: ansible_distribution == "Ubuntu"


- hosts: webservers
  become: true
  tasks:
   - name: Install apache package & php for Ubuntu
     tags: apache,apache2,ubuntu
     apt:
       name:
        - apache2
        - libapache2-mod-php
       state: latest
     when: ansible_distribution == "Ubuntu"
  
   - name: Install apache package & php for CentOS
     tags: apache,httpd,centos
     yum:
       name: 
        - httpd
        - php
       state: latest
     when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks: 

    - name: install mariadb package (CentOS)
      tags: db,mariadb,centos
      yum:
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS"
    

    - name: install mariadb package Ubuntu
      tags: db,mariadb,ubuntu
      apt:
        name: mariadb
        state: latest
      when: ansible_distribution == "Ubuntu"
     
- hosts: fileservers
  become: true
  tasks: 
    - name: install samba package
      tags: samba
      package:
        name: samba
        state: latest 
